site_name: TheHive Project Documentation

# mkdocs.yml
site_url: https://thehive-project.github.io/docs
# theme:
#   name: "material"
theme:
  name: material
  custom_dir: ./overrides/
  palette:
    scheme: default
  logo: 'images/thehive.png'
  features:
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
  palette:
    primary: 'red'
    # accent: red


plugins:
  - git-revision-date-localized:
      type: datetime
  - awesome-pages

  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      # watch:
      #   - thehive4py

# extra_css:
#   - custom.css

extra:
  social:
    - icon: fontawesome/solid/house
      link: "https://www.strangebee.com"
    - icon: fontawesome/brands/wordpress
      link: "https://blog.strangebee.com"
    - icon: fontawesome/brands/discord
      link: "https://chat.thehive-project.org"
# repo_name: "StrrangeBee/docs"
# repo_url: "https://github.com/strangebee.com/docs"
markdown_extensions:
    - toc:
        permalink: "#"
    - attr_list
    - codehilite
    - admonition
    - pymdownx.critic
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.details
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
